/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface SsfButton {
    /**
    * Caption to show on the button
    */
    'caption': string;
  }
  interface SsfButtonAttributes extends StencilHTMLAttributes {
    /**
    * Caption to show on the button
    */
    'caption'?: string;
  }

  interface SsfCheckbox {
    /**
    * Caption to show on the checkbox
    */
    'caption': string;
  }
  interface SsfCheckboxAttributes extends StencilHTMLAttributes {
    /**
    * Caption to show on the checkbox
    */
    'caption'?: string;
  }

  interface SsfLogin {
    /**
    * URL for EVRY Login client
    */
    'evryLoginURL': string;
    /**
    * The host to SSF Login Services
    */
    'ssfLoginServiceHost': string;
    /**
    * Use secure connection
    */
    'useSecureConnection': boolean;
  }
  interface SsfLoginAttributes extends StencilHTMLAttributes {
    /**
    * URL for EVRY Login client
    */
    'evryLoginURL'?: string;
    /**
    * The host to SSF Login Services
    */
    'ssfLoginServiceHost'?: string;
    /**
    * Use secure connection
    */
    'useSecureConnection'?: boolean;
  }

  interface SsfQrCode {
    'autoColor': boolean;
    'backgroundDimming': string;
    'bgSrc': string;
    'binarize': boolean;
    'binarizeThreshold': number;
    'callback': Function;
    'colorDark': string;
    'colorLight': string;
    'dotScale': number;
    'logoCornerRadius': number;
    'logoScale': number;
    'logoSrc': string;
    'margin': number;
    'qid': string;
    'size': number;
    'text': string;
    'whiteMargin': boolean;
  }
  interface SsfQrCodeAttributes extends StencilHTMLAttributes {
    'autoColor'?: boolean;
    'backgroundDimming'?: string;
    'bgSrc'?: string;
    'binarize'?: boolean;
    'binarizeThreshold'?: number;
    'callback'?: Function;
    'colorDark'?: string;
    'colorLight'?: string;
    'dotScale'?: number;
    'logoCornerRadius'?: number;
    'logoScale'?: number;
    'logoSrc'?: string;
    'margin'?: number;
    'qid'?: string;
    'size'?: number;
    'text'?: string;
    'whiteMargin'?: boolean;
  }
}

declare global {
  interface StencilElementInterfaces {
    'SsfButton': Components.SsfButton;
    'SsfCheckbox': Components.SsfCheckbox;
    'SsfLogin': Components.SsfLogin;
    'SsfQrCode': Components.SsfQrCode;
  }

  interface StencilIntrinsicElements {
    'ssf-button': Components.SsfButtonAttributes;
    'ssf-checkbox': Components.SsfCheckboxAttributes;
    'ssf-login': Components.SsfLoginAttributes;
    'ssf-qr-code': Components.SsfQrCodeAttributes;
  }


  interface HTMLSsfButtonElement extends Components.SsfButton, HTMLStencilElement {}
  var HTMLSsfButtonElement: {
    prototype: HTMLSsfButtonElement;
    new (): HTMLSsfButtonElement;
  };

  interface HTMLSsfCheckboxElement extends Components.SsfCheckbox, HTMLStencilElement {}
  var HTMLSsfCheckboxElement: {
    prototype: HTMLSsfCheckboxElement;
    new (): HTMLSsfCheckboxElement;
  };

  interface HTMLSsfLoginElement extends Components.SsfLogin, HTMLStencilElement {}
  var HTMLSsfLoginElement: {
    prototype: HTMLSsfLoginElement;
    new (): HTMLSsfLoginElement;
  };

  interface HTMLSsfQrCodeElement extends Components.SsfQrCode, HTMLStencilElement {}
  var HTMLSsfQrCodeElement: {
    prototype: HTMLSsfQrCodeElement;
    new (): HTMLSsfQrCodeElement;
  };

  interface HTMLElementTagNameMap {
    'ssf-button': HTMLSsfButtonElement
    'ssf-checkbox': HTMLSsfCheckboxElement
    'ssf-login': HTMLSsfLoginElement
    'ssf-qr-code': HTMLSsfQrCodeElement
  }

  interface ElementTagNameMap {
    'ssf-button': HTMLSsfButtonElement;
    'ssf-checkbox': HTMLSsfCheckboxElement;
    'ssf-login': HTMLSsfLoginElement;
    'ssf-qr-code': HTMLSsfQrCodeElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
